name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
        working-directory: ./starting-project

      - name: Run tests
        run: npm run test
        working-directory: ./starting-project
